version: "3.8"

services:
  web:
    build: ./hostel_management
    command: gunicorn hostel_management.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./hostel_management/:/usr/src/app/
    ports:
      - 8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./hostel_management
    command: celery -A hostel_management worker -l info
    volumes:
      - ./hostel_management/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  celery-beat:
    build: ./hostel_management
    command: celery -A hostel_management beat -l info
    volumes:
      - ./hostel_management/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
