# Generated by Django 4.1.7 on 2023-06-19 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_hostelroom_absentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentattendance',
            name='dateAbsent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
