# Generated by Django 4.1.7 on 2023-06-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_absentattendance_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Room_Number',
        ),
    ]
