# Generated by Django 4.1.7 on 2023-06-23 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_student_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='AdminApproved',
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
